# Generated by Django 5.0.7 on 2025-09-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_chairs_room_equipment_room_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='chairs',
        ),
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_attendees',
        ),
        migrations.RemoveField(
            model_name='room',
            name='projector',
        ),
        migrations.RemoveField(
            model_name='room',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tables',
        ),
    ]
