# Generated by Django 5.0.7 on 2025-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_room_capacity_room_chairs_room_image_room_projector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangerequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
