# Generated by Django 5.0.7 on 2025-09-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_passwordchangerequest_notified'),
    ]

    operations = [
    ]
