# Generated by Django 5.0.7 on 2025-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_passwordchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chairs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.TextField(blank=True, help_text='Comma-separated list of other equipment'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='speakers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='tables',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
